### ISSUE TITLE
Reopening of websocket does not work as expected due to websockets being not reusable

### ISSUE THREAD

**Issue by xenji** [xenji/homee_exporter#12]
```Mar 05 15:13:04 srv env[27516]: Exception in thread "Thread-1" java.lang.IllegalStateException: WebSocketClient objects are not reuseable
Mar 05 15:13:04 srv env[27516]:         at org.java_websocket.client.WebSocketClient.connect(WebSocketClient.java:166)
Mar 05 15:13:04 srv env[27516]:         at org.java_websocket.client.WebSocketClient.connectBlocking(WebSocketClient.java:177)
Mar 05 15:13:04 srv env[27516]:         at com.github.xenji.homee.api.HomeeWsClient.onClose(network.kt:53)
Mar 05 15:13:04 srv env[27516]:         at org.java_websocket.client.WebSocketClient.onWebsocketClose(WebSocketClient.java:391)
Mar 05 15:13:04 srv env[27516]:         at org.java_websocket.WebSocketImpl.closeConnection(WebSocketImpl.java:504)
Mar 05 15:13:04 srv env[27516]:         at org.java_websocket.WebSocketImpl.closeConnection(WebSocketImpl.java:515)
Mar 05 15:13:04 srv env[27516]:         at org.java_websocket.WebSocketImpl.eot(WebSocketImpl.java:563)
Mar 05 15:13:04 srv env[27516]:         at org.java_websocket.client.WebSocketClient.run(WebSocketClient.java:289)
Mar 05 15:13:04 srv env[27516]:         at java.lang.Thread.run(Thread.java:748)
Mar 05 15:13:06 srv env[27516]: 2018-03-05 15:13:06 [Thread-4] TRACE c.g.xenji.homee.api.HomeeWsClient - sending ping
Mar 05 15:13:06 srv env[27516]: Exception in thread "Thread-4" org.java_websocket.exceptions.WebsocketNotConnectedException
Mar 05 15:13:06 srv env[27516]:         at org.java_websocket.WebSocketImpl.send(WebSocketImpl.java:608)
Mar 05 15:13:06 srv env[27516]:         at org.java_websocket.WebSocketImpl.sendFrame(WebSocketImpl.java:634)
Mar 05 15:13:06 srv env[27516]:         at org.java_websocket.WebSocketImpl.sendPing(WebSocketImpl.java:641)
Mar 05 15:13:06 srv env[27516]:         at org.java_websocket.client.WebSocketClient.sendPing(WebSocketClient.java:237)
Mar 05 15:13:06 srv env[27516]:         at com.github.xenji.homee.api.HomeeWsClient$onOpen$1.invoke(network.kt:37)
Mar 05 15:13:06 srv env[27516]:         at com.github.xenji.homee.api.HomeeWsClient$onOpen$1.invoke(network.kt:23)
Mar 05 15:13:06 srv env[27516]:         at kotlin.concurrent.ThreadsKt$thread$thread$1.run(Thread.kt:18)
Mar 05 15:13:11 srv env[27516]: Exception in thread "Thread-5" org.java_websocket.exceptions.WebsocketNotConnectedException
Mar 05 15:13:11 srv env[27516]:         at org.java_websocket.WebSocketImpl.send(WebSocketImpl.java:608)
Mar 05 15:13:11 srv env[27516]:         at org.java_websocket.WebSocketImpl.send(WebSocketImpl.java:585)
Mar 05 15:13:11 srv env[27516]:         at org.java_websocket.client.WebSocketClient.send(WebSocketClient.java:207)
Mar 05 15:13:11 srv env[27516]:         at com.github.xenji.homee.ExporterKt$main$1$2$2.invoke(exporter.kt:29)
Mar 05 15:13:11 srv env[27516]:         at com.github.xenji.homee.ExporterKt$main$1$2$2.invoke(exporter.kt)
Mar 05 15:13:11 srv env[27516]:         at kotlin.concurrent.ThreadsKt$thread$thread$1.run(Thread.kt:18)```

**Comment by xenji** [comment]
Fixed with 0.2.0
